#!/usr/bin/env bash

set -e

if [ "$#" -lt 1 ]; then
    echo "Usage: ./secrets-init <vault_token>"
    exit 1
fi

export VAULT_TOKEN="$1"

if [ ! -f "secrets.yaml" ]; then
    echo "Error: secrets.yaml not found in the current directory."
    exit 1
fi

echo "Injecting Vault token into secrets.yaml..."
yq -i '
  (select(.kind == "Secret") | .stringData.VAULT_TOKEN) = env(VAULT_TOKEN)
' secrets.yaml

echo "Success! Secrets bootstrapping done."
