---
apiVersion: v1
kind: Namespace
metadata:
  name: secrets-manager
---
apiVersion: v1
kind: Secret
metadata:
  name: transit-unseal-secret
  namespace: secrets-manager
type: Opaque
stringData:
  VAULT_TOKEN: "s.u77iGb2MWzfit5Uck7rrS6x7"
