apiVersion: v1
kind: ConfigMap
metadata:
  name: global-vars
  namespace: flux-system
data:
  DOMAIN_ROOT: "local"
  DOMAIN_AUTH: "auth.local"
  DOMAIN_MONITORING: "metrics.local"
  DOMAIN_SECRETS: "secretsman.local"
