---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/Portfolio-Solver-Platform/gateway.git
  ref:
    branch: wip-rm-secrets-manager-route
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-crds
  namespace: flux-system
spec:
  interval: 10m
  path: ./crds
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: gateway
    namespace: flux-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gateway
  namespace: gateway
spec:
  interval: 5m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: ./helm/
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: gateway
        namespace: flux-system
  values:
    keycloak:
      hostname: ${DOMAIN_AUTH}
    grafana:
      hostname: ${DOMAIN_MONITORING}
    secretsManager:
      hostname: ${DOMAIN_SECRETS}
    gateway:
      hostname: ${DOMAIN_ROOT}
      https:
        certificates:
          root: ${TLS_CERTIFICATE_NAME_ROOT}
          keycloak: ${TLS_CERTIFICATE_NAME_AUTH}
          grafana: ${TLS_CERTIFICATE_NAME_MONITORING}
          secrets: ${TLS_CERTIFICATE_NAME_SECRETS}
  valuesFrom:
    - kind: ConfigMap
      name: gateway-vars
      valuesKey: ipAddress
      targetPath: gateway.ipAddress.value
      optional: true
