apiVersion: v1
kind: Namespace
metadata:
  name: secrets-manager
  labels:
    psp.io/encrypt: "true"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: secrets-manager
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/Portfolio-Solver-Platform/secrets-manager.git
  ref:
    branch: main
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: secrets-manager
  namespace: secrets-manager
spec:
  interval: 5m
  driftDetection:
    mode: warn
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  upgrade:
    crds: CreateReplace # update CRDs when upgrading
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  chart:
    spec:
      chart: ./helm/
      sourceRef:
        kind: GitRepository
        name: secrets-manager
        namespace: flux-system

      reconcileStrategy: Revision # Reconcile on file changes, not Helm chart version changes
      valuesFiles:
        - ./helm/values.yaml
