---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../prod/
  - ./secrets-manager-vars.yaml

patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: secrets-manager
        namespace: secrets-manager
      spec:
        chart:
          spec:
            valuesFiles:
              - ./helm/values.yaml
              - ./helm/values-dev.yaml
  - patch: |-
      apiVersion: infra.contrib.fluxcd.io/v1alpha2
      kind: Terraform
      metadata:
        name: secrets-manager-setup
        namespace: flux-system
      spec:
        vars:
          - name: url
            value: "http://secrets-manager-openbao.secrets-manager.svc.cluster.local:8200"
          - name: token_name
            value: "tofu-controller"
