apiVersion: v1
kind: ConfigMap
metadata:
  name: global-vars
  namespace: flux-system
data:
  DOMAIN_ROOT: "psp.jonasbork.com"
  DOMAIN_AUTH_MANAGER: "auth.psp.jonasbork.com"
  DOMAIN_MONITORING: "metrics.psp.jonasbork.com"
  DOMAIN_SECRETS: "secrets.psp.jonasbork.com"
