app:
  debug: false  # Disable auto-creation in production

hpa:
  minReplicas: 2

postgres:
  replicaCount: 2
  service:
    name: {{.DB_HOST}}
    port: {{.DB_PORT}}
  database:
    name: {{.DB_NAME}}
    user: {{.DB_USER}}
    password: {{.DB_PASSWORD}} 
  persistence:
    size: "5Gi"

rabbitmq:
  user: guest
  password: guest
