#!/usr/bin/env bash

set -euo pipefail

if [ -z "$1" ]; then
    echo "Error: Transit token not provided."
    echo "Usage: $0 <transit-token>"
    exit 1
fi

TOKEN="$1"

cd ../secrets-manager
./scripts/init-prepare "$TOKEN"

