#!/usr/bin/env bash

set -euo pipefail

if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <host>"
    exit 1
fi

export TRANSIT_HOST="$1"
SECRET_PATH="./scripts/helpers/secrets-manager-transit-vars.yaml"

if [ ! -f "$SECRET_PATH" ]; then
    echo "Error: $SECRET_PATH not found."
    exit 1
fi

echo "Applying secret to cluster..."
yq '
  (select(.kind == "Secret") | .stringData.host) = env(TRANSIT_HOST)
' "$SECRET_PATH" | kubectl apply -f -

echo "Success! Applied secret with host '$TRANSIT_HOST'"

