apiVersion: v1
kind: Secret
metadata:
  name: secrets-manager-vars
  namespace: flux-system
stringData:
  token: "root"
  auth_manager_bootstrap_admin_username: "admin"
  auth_manager_bootstrap_admin_password: "admin"
  auth_manager_bootstrap_service_secret: "admin"
  auth_manager_admin_app_secret: "admin"
