apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: solver-director
  namespace: psp
spec:
  releaseName: solver-director
  interval: 5m
  targetNamespace: psp
  chart:
    spec:
      chart: ./charts/solver-director/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    image: ghcr.io/portfolio-solver-platform/solver-director:main-dc5abc1d-20260320141518
    service:
      name: solver-director
