apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: solver-controller
  namespace: psp
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/app/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    image: ghcr.io/portfolio-solver-platform/solver-controller:main-55b1a873-20260317135116
    service:
      name: solver-controller
