apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: user
  namespace: flux-system
spec:
  interval: 10m
  url: oci://ghcr.io/portfolio-solver-platform/charts/user
  ref:
    tag: "1.1.0"
    digest: "sha256:9a357e7ad7d348aa7d05ec65dad31eb034127c915c20ffb3c692e936f6837579"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: user
  namespace: psp
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: user
    namespace: flux-system
