apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: user
  namespace: psp
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/app/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    image: ghcr.io/portfolio-solver-platform/user:main-5abab310-20260317083224
    service:
      name: user
