apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../templates/namespace/
  - ./deployment.yaml

namespace: keycloak

patches:
  - target:
      version: v1
      kind: Namespace
      name: placeholder
    patch: |-
      - op: replace
        path: /metadata/name
        value: keycloak
