name: Validate

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  validate:
    name: Validate configuration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        
      - name: Setup Nix Magic Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run Validation Script
        run: nix develop --command ./tests/validate-flux.sh
