name: Push Docker image

on:
  workflow_call:
    inputs:
      image_name:
        description: 'The name of the Docker image (e.g., user)'
        required: true
        type: string
      registry:
        description: 'The container registry to push to'
        required: false
        type: string
        default: 'ghcr.io/portfolio-solver-platform'
      main_branch_name:
        description: 'The branch name that receives the latest tag'
        required: false
        type: string
        default: 'main'

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      REGISTRY: ${{ inputs.registry }}
      IMAGE_NAME: ${{ inputs.image_name }}
      MAIN_BRANCH_NAME: ${{ inputs.main_branch_name }}

    steps:
      - name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF_NAME//\//-}
          sha=${GITHUB_SHA::8}
          ts=$(date +'%Y%m%d%H%M%S')
          echo "BUILD_TAG=${branch}-${sha}-${ts}" >> "$GITHUB_ENV"

      - name: Generate Tags
        run: |
          IMAGE="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_TAG }}"
          TAGS="$IMAGE"

          if [ "$GITHUB_REF_NAME" == "${{ env.MAIN_BRANCH_NAME }}" ]; then
            TAGS="$TAGS,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
            echo "Building from main branch. 'latest' tag will be applied."
          fi

          echo "IMAGE=$IMAGE" >> "$GITHUB_ENV"
          echo "DOCKER_TAGS=$TAGS" >> "$GITHUB_ENV"

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          context: .
          pull: true
          push: true
          tags: ${{ env.DOCKER_TAGS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max,ignore-error=true

